### ISSUE TITLE
Contact Form Interactividad

### ISSUE THREAD

**Issue by jorgemamani1618** [jorgemamani1618/hbicom2021#4]
Agregar una notificación que le diga al usuario que su mensaje se ha enviado:
"Mensaje Enviado"

Validación de campos:
 - Al presionar SEND y si  los campos no están completos mostrar un mensaje que diga: "Complete todos los campos: "
 - Validación de formato de correo (@ .) "Verifique su correo"
 
 
![image](https://user-images.githubusercontent.com/73918869/112708593-d70f6300-8e80-11eb-9f8f-16b29622d4fb.png)

**Comment by BraulioJose18** [comment]
Funcionalidad terminada
